name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Create virtual environment and install dependencies
      run: |
        make uv-sync

    - name: Run unit tests
      run: |
        make uv-test

  rust-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Rust crate
      run: |
        cd trae-agent-rs
        cargo build --locked --verbose
